image:
  name: hashicorp/terraform:1.0.0
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

before_script:
  - rm -rf .terraform
  - terraform --version
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - ./planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  only:
    - master
  when: manual
  dependencies:
    - plan

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve
  only:
    - master
  when: manual
  dependencies:
    - plan
